apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: amis-kho-phim-backend
  namespace: amis-kho-phim
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: amis-kho-phim-backend
